version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - task-service
      - client
    networks:
      - task-network
    restart: unless-stopped

  user-service:
    image: upansh522/task_management:user_service
    environment:
      - NODE_ENV=production
      - PORT=8001
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=http://localhost 
    expose:
      - "8001"
    restart: unless-stopped
    networks:
      - task-network

  task-service:
    image: upansh522/task_management:task_service
    environment:
      - NODE_ENV=production
      - PORT=8002
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=http://localhost 
      - USER_SERVICE_URL=http://nginx/api/users
    expose:
      - "8002"
    depends_on:
      - user-service
    restart: unless-stopped
    networks:
      - task-network

  client:   
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENT_URL: http://localhost
        NEXT_PUBLIC_USER_SERVICE_URL: http://localhost/api/users
        NEXT_PUBLIC_TASK_SERVICE_URL: http://localhost/api/tasks
    expose:
      - "3000"
    depends_on:
      - user-service
      - task-service
    restart: unless-stopped
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
